### ISSUE TITLE
demo  调整gradle版本运行报错这个信息

### ISSUE THREAD

**Issue by zhangxiaojin770** [Dawish/DxKit#1]
distributionUrl=https\://mirrors.cloud.tencent.com/gradle/gradle-6.7.1-bin.zip
插件：classpath "com.android.tools.build:gradle:4.2.1"

请问我需要怎么调整呢

Caused by: com.android.tools.r8.utils.b0: java.lang.ArrayIndexOutOfBoundsException: 69
at com.android.tools.r8.utils.b0.a(SourceFile:6)
		at com.android.tools.r8.utils.a0.a(SourceFile:126)
		at com.android.tools.r8.ir.conversion.T.c(SourceFile:12)
		at com.android.tools.r8.ir.conversion.T.a(SourceFile:477)
		at com.android.tools.r8.ir.conversion.T.a(SourceFile:414)
		at com.android.tools.r8.graph.n0.b(SourceFile:2)
		at com.android.tools.r8.graph.t1.b(SourceFile:4)
		at com.android.tools.r8.graph.u1.a(SourceFile:3)
		at com.android.tools.r8.graph.s1.d(SourceFile:3)
		at com.android.tools.r8.graph.u1.a(SourceFile:1)
		at com.android.tools.r8.graph.t1.b(SourceFile:2)
		at com.android.tools.r8.graph.n0.b(SourceFile:1)
		at com.android.tools.r8.ir.conversion.T.b(SourceFile:17)
		at com.android.tools.r8.utils.c1.a(SourceFile:36)
		at com.android.tools.r8.utils.c1.a(SourceFile:41)
		at com.android.tools.r8.utils.c1.a(SourceFile:35)
		at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
		at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:69)
		at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
		at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:322)
		at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
		at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:66)
		at com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:36)
		at com.android.tools.r8.utils.c1.a(SourceFile:34)
		at java.util.ArrayList.forEach(ArrayList.java:1259)
		at com.android.tools.r8.utils.c1.a(SourceFile:6)
		... 46 more
	Caused by: [CIRCULAR REFERENCE: java.lang.ArrayIndexOutOfBoundsException: 69]

**Comment by Dawish** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
